### ISSUE TITLE
剑心全局设置、茗依全局设置勾选后无法成功复制

### ISSUE THREAD

**Issue by cyt7732** [X3ZvaWQ/JX3SyncAssistant#1]
在复制配置过程中，若勾选剑心全局设置、茗依全局设置，则无法复制配置成功。

**Comment by x3zvawq** [comment]
请问可以提供报错信息么？你只需要重新操作一次，然后把窗口向下拉伸可以看到一片黑色的日志区，将里面的内容复制给我。

**Comment by cyt7732** [comment]
Log
getZipFromUserdata() Run Error!
未能找到路径“E:\剑网3\Game\JX3\bin\zhcn_hd\interface\MY#DATA\!all-users@zhcn\userdata\TargetMon”的一部分。
   在 JX3SyncAssistant.Helper.GetZipFromUserdata(String SourceData, String zip, Dictionary`2 roleInfo, Dictionary`2 contain_options, TextBox logPanel)
   在 JX3SyncAssistant.MainWindow.Go_Click(Object sender, RoutedEventArgs e)

**Comment by x3zvawq** [comment]
该问题已修复 于v0.2.1版本
